version: '3'

services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - frontend
      - postgres
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/static/:/app/backend/static/
      - ./backend/media/:/app/backend/media/
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'frontend.com -> http://frontend:3000, backend.com -> http://backend:8000' #ドメインは例です。
      STAGE: 'production'
    volumes:
      - https-portal-data:/var/lib/https-portal # ここを書いていなかった

volumes:  # ここを書いていなかった
  https-portal-data:  # ここを書いていなかった

