# Generated by Django 4.2.7 on 2024-01-11 08:56

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="タイトル")),
                ("date", models.DateField()),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to=blog.models.upload_to
                    ),
                ),
                ("text", models.TextField()),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="URL"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名前")),
                ("email", models.EmailField(max_length=100, verbose_name="メールアドレス")),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="タイトル")),
                ("date", models.DateField()),
                ("category", models.CharField(max_length=20, verbose_name="カテゴリ")),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="タイトル")),
                ("date", models.DateField()),
                ("thumbnail", models.ImageField(upload_to=blog.models.upload_to)),
                ("text", models.TextField()),
                ("url", models.CharField(max_length=100, verbose_name="URL")),
            ],
        ),
    ]
